[2022-05-19 01:11:06,451] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: model_level_dbt_great_expectations_dag.great_expectations_sources.sources.jaffle_shop__orders scheduled__2022-05-17T23:51:54.527642+00:00 [queued]>
[2022-05-19 01:11:06,546] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: model_level_dbt_great_expectations_dag.great_expectations_sources.sources.jaffle_shop__orders scheduled__2022-05-17T23:51:54.527642+00:00 [queued]>
[2022-05-19 01:11:06,547] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 01:11:06,548] {taskinstance.py:1242} INFO - Starting attempt 2 of 5
[2022-05-19 01:11:06,554] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 01:11:06,636] {taskinstance.py:1262} INFO - Executing <Task(GreatExpectationsOperator): great_expectations_sources.sources.jaffle_shop__orders> on 2022-05-17 23:51:54.527642+00:00
[2022-05-19 01:11:07,219] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'model_level_dbt_great_expectations_dag', 'great_expectations_sources.sources.jaffle_shop__orders', 'scheduled__2022-05-17T23:51:54.527642+00:00', '--job-id', '276', '--raw', '--subdir', 'DAGS_FOLDER/model_level_dbt_great_expectations_dag.py', '--cfg-path', '/tmp/tmp_o4oqeoj', '--error-file', '/tmp/tmpqezxrjon']
[2022-05-19 01:11:07,192] {standard_task_runner.py:52} INFO - Started process 232 to run task
[2022-05-19 01:11:07,226] {standard_task_runner.py:77} INFO - Job 276: Subtask great_expectations_sources.sources.jaffle_shop__orders
[2022-05-19 01:11:08,605] {logging_mixin.py:109} INFO - Running <TaskInstance: model_level_dbt_great_expectations_dag.great_expectations_sources.sources.jaffle_shop__orders scheduled__2022-05-17T23:51:54.527642+00:00 [running]> on host 41cba24e2fbb
[2022-05-19 01:11:10,055] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=luciano.naveiro
AIRFLOW_CTX_DAG_ID=model_level_dbt_great_expectations_dag
AIRFLOW_CTX_TASK_ID=great_expectations_sources.sources.jaffle_shop__orders
AIRFLOW_CTX_EXECUTION_DATE=2022-05-17T23:51:54.527642+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-17T23:51:54.527642+00:00
[2022-05-19 01:11:10,080] {great_expectations.py:122} INFO - Running validation with Great Expectations...
[2022-05-19 01:11:10,084] {great_expectations.py:125} INFO - Ensuring data context is valid...
[2022-05-19 01:11:18,408] {sqlalchemy_execution_engine.py:404} WARNING - schema_name specified creating a URL with schema is not supported. Set a default schema on the user connecting to your database.
[2022-05-19 01:11:18,510] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/great_expectations/datasource/data_connector/runtime_data_connector.py:135 DeprecationWarning: Specifying batch_identifiers as part of the RuntimeDataConnector config is deprecated as of v0.15.1 and will be removed by v0.18. Please configure batch_identifiers as part of Assets instead.
[2022-05-19 01:11:28,722] {validator.py:1669} INFO - 	15 expectation(s) included in expectation_suite.
[2022-05-19 01:11:29,460] {logging_mixin.py:109} WARNING - Calculating Metrics:   0%|          | 0/33 [00:00<?, ?it/s]
[2022-05-19 01:11:29,461] {logging_mixin.py:109} WARNING - Calculating Metrics:   0%|          | 0/33 [00:00<?, ?it/s]
[2022-05-19 01:11:29,480] {logging_mixin.py:109} WARNING - Calculating Metrics:   6%|6         | 2/33 [00:00<00:00, 106.80it/s]
[2022-05-19 01:11:29,555] {logging_mixin.py:109} WARNING - Calculating Metrics:  12%|#2        | 4/33 [00:00<00:00, 43.61it/s] 
[2022-05-19 01:11:29,636] {logging_mixin.py:109} WARNING - Calculating Metrics:  36%|###6      | 12/33 [00:00<00:00, 69.83it/s]
[2022-05-19 01:11:29,638] {logging_mixin.py:109} WARNING - Calculating Metrics:  36%|###6      | 12/33 [00:00<00:00, 69.83it/s]
[2022-05-19 01:11:30,116] {logging_mixin.py:109} WARNING - Calculating Metrics:  82%|########1 | 27/33 [00:00<00:00, 39.05it/s]
[2022-05-19 01:11:30,129] {logging_mixin.py:109} WARNING - Calculating Metrics:  82%|########1 | 27/33 [00:00<00:00, 39.05it/s]
[2022-05-19 01:11:30,467] {logging_mixin.py:109} WARNING - Calculating Metrics: 100%|##########| 33/33 [00:01<00:00, 28.91it/s]
[2022-05-19 01:11:30,473] {logging_mixin.py:109} WARNING - Calculating Metrics: 100%|##########| 33/33 [00:01<00:00, 28.91it/s]
[2022-05-19 01:11:30,875] {logging_mixin.py:109} WARNING - Calculating Metrics: 100%|##########| 33/33 [00:01<00:00, 28.91it/s]
[2022-05-19 01:11:30,877] {logging_mixin.py:109} WARNING - Calculating Metrics: 100%|##########| 33/33 [00:01<00:00, 23.31it/s]
[2022-05-19 01:11:30,878] {logging_mixin.py:109} WARNING - 
[2022-05-19 01:11:54,609] {great_expectations.py:197} INFO - Validation with Great Expectations successful.
[2022-05-19 01:11:55,134] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=model_level_dbt_great_expectations_dag, task_id=great_expectations_sources.sources.jaffle_shop__orders, execution_date=20220517T235154, start_date=20220519T011106, end_date=20220519T011155
[2022-05-19 01:11:55,548] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-19 01:11:56,262] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
