[2022-05-15 01:30:31,916] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: dbt_dag.test scheduled__2021-12-30T00:00:00+00:00 [queued]>
[2022-05-15 01:30:33,866] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: dbt_dag.test scheduled__2021-12-30T00:00:00+00:00 [queued]>
[2022-05-15 01:30:33,871] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-05-15 01:30:33,883] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-05-15 01:30:33,924] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-15 01:30:34,348] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): test> on 2021-12-30 00:00:00+00:00
[2022-05-15 01:30:34,522] {standard_task_runner.py:52} INFO - Started process 2590 to run task
[2022-05-15 01:30:34,790] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'test', 'scheduled__2021-12-30T00:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpi7g4nao5', '--error-file', '/tmp/tmp236welhr']
[2022-05-15 01:30:34,815] {standard_task_runner.py:77} INFO - Job 46: Subtask test
[2022-05-15 01:30:36,979] {logging_mixin.py:109} INFO - Running <TaskInstance: dbt_dag.test scheduled__2021-12-30T00:00:00+00:00 [running]> on host b0833397c3cf
[2022-05-15 01:30:38,841] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_dag
AIRFLOW_CTX_TASK_ID=test
AIRFLOW_CTX_EXECUTION_DATE=2021-12-30T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-30T00:00:00+00:00
[2022-05-15 01:30:38,866] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-15 01:30:38,883] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n        pwd\n        ']
[2022-05-15 01:30:39,177] {subprocess.py:85} INFO - Output:
[2022-05-15 01:30:39,318] {subprocess.py:89} INFO - /tmp/***tmps65exmi0
[2022-05-15 01:30:39,352] {subprocess.py:93} INFO - Command exited with return code 0
[2022-05-15 01:30:47,124] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=dbt_dag, task_id=test, execution_date=20211230T000000, start_date=20220515T013032, end_date=20220515T013047
[2022-05-15 01:30:48,266] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-15 01:30:48,904] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-15 01:30:49,190] {dagrun.py:527} ERROR - Marking run <DagRun dbt_dag @ 2021-12-30 00:00:00+00:00: scheduled__2021-12-30T00:00:00+00:00, externally triggered: False> failed
[2022-05-15 01:30:49,205] {dagrun.py:602} INFO - DagRun Finished: dag_id=dbt_dag, execution_date=2021-12-30 00:00:00+00:00, run_id=scheduled__2021-12-30T00:00:00+00:00, run_start_date=2022-05-15 01:30:12.114131+00:00, run_end_date=2022-05-15 01:30:49.204932+00:00, run_duration=37.090801, state=failed, external_trigger=False, run_type=scheduled, data_interval_start=2021-12-30 00:00:00+00:00, data_interval_end=2021-12-31 00:00:00+00:00, dag_hash=08ba76bc4de643e0df82526ee6b4f9f1
