[2022-06-04 20:37:34,291] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: model_level_dbt_great_expectations_dag.dbt_validate.dbt_debug scheduled__2022-06-03T02:56:49.432006+00:00 [queued]>
[2022-06-04 20:37:34,310] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: model_level_dbt_great_expectations_dag.dbt_validate.dbt_debug scheduled__2022-06-03T02:56:49.432006+00:00 [queued]>
[2022-06-04 20:37:34,312] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-06-04 20:37:34,314] {taskinstance.py:1242} INFO - Starting attempt 2 of 5
[2022-06-04 20:37:34,315] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-06-04 20:37:34,334] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): dbt_validate.dbt_debug> on 2022-06-03 02:56:49.432006+00:00
[2022-06-04 20:37:34,346] {standard_task_runner.py:52} INFO - Started process 985 to run task
[2022-06-04 20:37:34,353] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'model_level_dbt_great_expectations_dag', 'dbt_validate.dbt_debug', 'scheduled__2022-06-03T02:56:49.432006+00:00', '--job-id', '302', '--raw', '--subdir', 'DAGS_FOLDER/model_level_dbt_great_expectations_dag.py', '--cfg-path', '/tmp/tmpkndi1sjg', '--error-file', '/tmp/tmpdtbt_ccr']
[2022-06-04 20:37:34,355] {standard_task_runner.py:77} INFO - Job 302: Subtask dbt_validate.dbt_debug
[2022-06-04 20:37:34,426] {logging_mixin.py:109} INFO - Running <TaskInstance: model_level_dbt_great_expectations_dag.dbt_validate.dbt_debug scheduled__2022-06-03T02:56:49.432006+00:00 [running]> on host 0c1ca7618279
[2022-06-04 20:37:34,501] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=luciano.naveiro
AIRFLOW_CTX_DAG_ID=model_level_dbt_great_expectations_dag
AIRFLOW_CTX_TASK_ID=dbt_validate.dbt_debug
AIRFLOW_CTX_EXECUTION_DATE=2022-06-03T02:56:49.432006+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-03T02:56:49.432006+00:00
[2022-06-04 20:37:34,505] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-04 20:37:34,508] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n        dbt debug --profiles-dir /opt/dbt/jaffle_shop --project-dir /opt/dbt/jaffle_shop\n        ']
[2022-06-04 20:37:34,538] {subprocess.py:85} INFO - Output:
[2022-06-04 20:37:39,194] {subprocess.py:89} INFO - 20:37:39  Running with dbt=1.1.0
[2022-06-04 20:37:40,482] {subprocess.py:89} INFO - dbt version: 1.1.0
[2022-06-04 20:37:40,483] {subprocess.py:89} INFO - python version: 3.7.12
[2022-06-04 20:37:40,485] {subprocess.py:89} INFO - python path: /usr/local/bin/python
[2022-06-04 20:37:40,485] {subprocess.py:89} INFO - os info: Linux-5.10.25-linuxkit-x86_64-with-debian-10.11
[2022-06-04 20:37:40,487] {subprocess.py:89} INFO - Using profiles.yml file at /opt/dbt/jaffle_shop/profiles.yml
[2022-06-04 20:37:40,488] {subprocess.py:89} INFO - Using dbt_project.yml file at /opt/dbt/jaffle_shop/dbt_project.yml
[2022-06-04 20:37:40,488] {subprocess.py:89} INFO - 
[2022-06-04 20:37:40,489] {subprocess.py:89} INFO - Configuration:
[2022-06-04 20:37:40,490] {subprocess.py:89} INFO -   profiles.yml file [[32mOK found and valid[0m]
[2022-06-04 20:37:40,491] {subprocess.py:89} INFO -   dbt_project.yml file [[32mOK found and valid[0m]
[2022-06-04 20:37:40,492] {subprocess.py:89} INFO - 
[2022-06-04 20:37:40,493] {subprocess.py:89} INFO - Required dependencies:
[2022-06-04 20:37:40,495] {subprocess.py:89} INFO -  - git [[32mOK found[0m]
[2022-06-04 20:37:40,497] {subprocess.py:89} INFO - 
[2022-06-04 20:37:40,498] {subprocess.py:89} INFO - Connection:
[2022-06-04 20:37:40,499] {subprocess.py:89} INFO -   host: postgres_local
[2022-06-04 20:37:40,500] {subprocess.py:89} INFO -   port: 5432
[2022-06-04 20:37:40,501] {subprocess.py:89} INFO -   user: docker
[2022-06-04 20:37:40,502] {subprocess.py:89} INFO -   database: raw
[2022-06-04 20:37:40,504] {subprocess.py:89} INFO -   schema: dev
[2022-06-04 20:37:40,505] {subprocess.py:89} INFO -   search_path: None
[2022-06-04 20:37:40,506] {subprocess.py:89} INFO -   keepalives_idle: 0
[2022-06-04 20:37:40,506] {subprocess.py:89} INFO -   sslmode: None
[2022-06-04 20:37:40,507] {subprocess.py:89} INFO -   Connection test: [[32mOK connection ok[0m]
[2022-06-04 20:37:40,508] {subprocess.py:89} INFO - 
[2022-06-04 20:37:40,509] {subprocess.py:89} INFO - [32mAll checks passed![0m
[2022-06-04 20:37:40,658] {subprocess.py:93} INFO - Command exited with return code 0
[2022-06-04 20:37:40,727] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=model_level_dbt_great_expectations_dag, task_id=dbt_validate.dbt_debug, execution_date=20220603T025649, start_date=20220604T203734, end_date=20220604T203740
[2022-06-04 20:37:40,777] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-06-04 20:37:40,834] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
