[2022-06-04 02:46:05,004] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: model_level_dbt_dag.dbt_validate.dbt_debug scheduled__2022-05-19T15:43:01.271269+00:00 [queued]>
[2022-06-04 02:46:05,161] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: model_level_dbt_dag.dbt_validate.dbt_debug scheduled__2022-05-19T15:43:01.271269+00:00 [queued]>
[2022-06-04 02:46:05,169] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-06-04 02:46:05,176] {taskinstance.py:1242} INFO - Starting attempt 1 of 4
[2022-06-04 02:46:05,183] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-06-04 02:46:05,379] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): dbt_validate.dbt_debug> on 2022-05-19 15:43:01.271269+00:00
[2022-06-04 02:46:05,436] {standard_task_runner.py:52} INFO - Started process 69 to run task
[2022-06-04 02:46:05,587] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'model_level_dbt_dag', 'dbt_validate.dbt_debug', 'scheduled__2022-05-19T15:43:01.271269+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/model_level_dbt_dag.py', '--cfg-path', '/tmp/tmpo6jcjtom', '--error-file', '/tmp/tmpbnlif8o0']
[2022-06-04 02:46:05,595] {standard_task_runner.py:77} INFO - Job 162: Subtask dbt_validate.dbt_debug
[2022-06-04 02:46:06,045] {logging_mixin.py:109} INFO - Running <TaskInstance: model_level_dbt_dag.dbt_validate.dbt_debug scheduled__2022-05-19T15:43:01.271269+00:00 [running]> on host 3d17a0db806e
[2022-06-04 02:46:06,342] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=luciano.naveiro
AIRFLOW_CTX_DAG_ID=model_level_dbt_dag
AIRFLOW_CTX_TASK_ID=dbt_validate.dbt_debug
AIRFLOW_CTX_EXECUTION_DATE=2022-05-19T15:43:01.271269+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-19T15:43:01.271269+00:00
[2022-06-04 02:46:06,366] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-04 02:46:06,377] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n        dbt debug --profiles-dir /opt/dbt/jaffle_shop --project-dir /opt/dbt/jaffle_shop\n        ']
[2022-06-04 02:46:06,492] {subprocess.py:85} INFO - Output:
[2022-06-04 02:46:24,996] {subprocess.py:89} INFO - 02:46:24  Running with dbt=1.1.0
[2022-06-04 02:46:27,395] {subprocess.py:89} INFO - dbt version: 1.1.0
[2022-06-04 02:46:27,405] {subprocess.py:89} INFO - python version: 3.7.12
[2022-06-04 02:46:27,427] {subprocess.py:89} INFO - python path: /usr/local/bin/python
[2022-06-04 02:46:27,442] {subprocess.py:89} INFO - os info: Linux-5.10.25-linuxkit-x86_64-with-debian-10.11
[2022-06-04 02:46:27,453] {subprocess.py:89} INFO - Using profiles.yml file at /opt/dbt/jaffle_shop/profiles.yml
[2022-06-04 02:46:27,469] {subprocess.py:89} INFO - Using dbt_project.yml file at /opt/dbt/jaffle_shop/dbt_project.yml
[2022-06-04 02:46:27,480] {subprocess.py:89} INFO - 
[2022-06-04 02:46:27,481] {subprocess.py:89} INFO - Configuration:
[2022-06-04 02:46:27,498] {subprocess.py:89} INFO -   profiles.yml file [[32mOK found and valid[0m]
[2022-06-04 02:46:27,499] {subprocess.py:89} INFO -   dbt_project.yml file [[32mOK found and valid[0m]
[2022-06-04 02:46:27,502] {subprocess.py:89} INFO - 
[2022-06-04 02:46:27,515] {subprocess.py:89} INFO - Required dependencies:
[2022-06-04 02:46:27,517] {subprocess.py:89} INFO -  - git [[32mOK found[0m]
[2022-06-04 02:46:27,534] {subprocess.py:89} INFO - 
[2022-06-04 02:46:27,536] {subprocess.py:89} INFO - Connection:
[2022-06-04 02:46:27,552] {subprocess.py:89} INFO -   host: postgres_local
[2022-06-04 02:46:27,554] {subprocess.py:89} INFO -   port: 5432
[2022-06-04 02:46:27,556] {subprocess.py:89} INFO -   user: docker
[2022-06-04 02:46:27,572] {subprocess.py:89} INFO -   database: raw
[2022-06-04 02:46:27,573] {subprocess.py:89} INFO -   schema: dev
[2022-06-04 02:46:27,575] {subprocess.py:89} INFO -   search_path: None
[2022-06-04 02:46:27,586] {subprocess.py:89} INFO -   keepalives_idle: 0
[2022-06-04 02:46:27,587] {subprocess.py:89} INFO -   sslmode: None
[2022-06-04 02:46:27,603] {subprocess.py:89} INFO -   Connection test: [[32mOK connection ok[0m]
[2022-06-04 02:46:27,606] {subprocess.py:89} INFO - 
[2022-06-04 02:46:27,623] {subprocess.py:89} INFO - [32mAll checks passed![0m
[2022-06-04 02:46:28,429] {subprocess.py:93} INFO - Command exited with return code 0
[2022-06-04 02:46:28,518] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=model_level_dbt_dag, task_id=dbt_validate.dbt_debug, execution_date=20220519T154301, start_date=20220604T024605, end_date=20220604T024628
[2022-06-04 02:46:28,652] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-06-04 02:46:28,872] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
